# Python Exercises for Hughes and Hase: Chapter 1


Python activities to complement Measurements and their Uncertainties, Chapter 1, "Errors in the physical sciences."

Author: J. S. Dodge, 2016 ©

## Preliminaries
Over the next few weeks, you will be assigned notebooks designed to teach you a bit of statistics and to acquaint you with the scientific programming language Python. Most modules contains questions related to the required textbook for this course, Measurements and their Uncertainties, by Hughes and Hase. Sections in the worksheet are numbered to be consistent with the text. Please read the corresponding section of the book before beginning the associated section of the worksheet and then do the questions, using the book as a reference as you work. 

<- Explain how to use Jupyter Notebooks to run Python script and also how to submit files on Canvas -> 


## Python basics

Review the following documentation pages to familiarize yourself with the basic elements of the Python language, integrated development environment (IDE) and Python libraries for data analysis.

* [Python Lectures](https://sfu.syzygy.ca/jupyter/hub/user-redirect/git-pull?repo=https://github.com/nleehone/PythonLectures.git&branch=master)

Additional resources: 
* [Getting Started With Jupyter Notebook for Python](https://medium.com/codingthesmartway-com-blog/getting-started-with-jupyter-notebook-for-python-4e7082bd5d46)

For MATLAB users:

* [NumPy for Matlab users](https://www.numpy.org/devdocs/user/numpy-for-matlab-users.html)

Python online documentation: 
* [Python 3.7.4 documentation](https://docs.python.org/3/tutorial/)


## Random number generation (RNG)

RNGs are wonderful tools for learning about statistics, simulating experiments, and even doing certain types of theoretical calculations. You might wonder how a computer, a completely deterministic machine, can generate random numbers. The short answer is that it does not; the functions use algorithms that are cleverly designed to produce numbers that satisfy most statistical requirements associated with randomness, but actually follow a well-defined sequence. If this sounds strange, you are not alone: the great 20th century mathematician John von Neumann wrote, "Anyone who considers arithmetical methods of producing random digits is, of course, in a state of sin." [J. von Neumann, NBS Applied Mathematics Series, (1951).](https://dornsifecms.usc.edu/assets/sites/520/docs/VonNeumann-ams12p36-38.pdf) 




Technically, the numbers produced by rand and randn are called pseudorandom numbers to distinguish them from their purer counterparts. A brief review of the algorithm used for rand is available in the short article ["Random Thoughts"](toBeAdded) by Cleve Moler; a more comprehensive and mathematical review of the subject is available in Don Knuth's [The Art of Computer Programming, volume 2: Seminumerical Algorithms](toBeAdded) , among others.

We'll use Python's random number generation capabilities to simulate experimental errors. In order to use random number in Python we need to use a library called ["random"](https://docs.python.org/3/library/random.html). This library contains several functions that deal with random number generation. One of these function is random.random(). This function returns random numbers that are uniformly distributed over \[0.0, 1.0).
Try to run the following cell multiple times. 

In [1]:
# import the essencial library
import random
# random(): return
print(random.random())
print(random.random())
print(random.random())
print(random.random())

0.8069477342138756
0.32258322549996266
0.5841092508956212
0.955899486034022


You will find that each time you get a different results. In order to make have reproducible results, we would like to used the same sequence of random numbers each time we run our code. In general this method is know as "random seed". In Python we can call this method(function) by [random.seed()](https://docs.python.org/3/library/random.html#random.seed). 
Try to run the following cell multiple times. 

In [2]:
# import the essencial library
import random
# initialize a pseudorandom number generator
random.seed(1)
# print a few random numbers
print(random.random())
print(random.random())
print(random.random())
print(random.random())

0.13436424411240122
0.8474337369372327
0.763774618976614
0.2550690257394217


## One-dimentional random number:
Sometime we want a one-dimensional **vector** of random numbers. We can use numpy to do so. numpy is one of the main libraries that deals with vectors in Python. In this library numpy.random.randn(n) generates an array(vector) of n random numbers from a uniform distribution over \[0, 1). 



In [3]:
# import the essential  library
import numpy
# initialize a pseudorandom number generator
numpy.random.seed(2)
# print some random victors of with length of 3
random_noise = numpy.random.randn(3000)
# print the fist 10 values in random_noise
print(random_noise[:10])


[-0.41675785 -0.05626683 -2.1361961   1.64027081 -1.79343559 -0.84174737
  0.50288142 -1.24528809 -1.05795222 -0.90900761]


## Plot histogram
Histogram plots are great visualization tools. In order to plot a histogram we need to import a library called matplotlib. Specifically we need to use a module called pyplot. We can import this module "import matplotlib.pyplot" also we can give it a local name. Additional reading: [How to import modules in Python 3](https://www.digitalocean.com/community/tutorials/how-to-import-modules-in-python-3).

In [4]:
# import matplotlib.pyplot and rename it "plt"
import matplotlib.pyplot as plt
# import numpy and rename it "np"
import numpy as np



plt.hist(random_noise, bins=20);

In the example above, random_noise is a normal distribution $$N(\mu, \sigma)$$
in which $\mu = 0$ and $\sigma=1$. 

How do you generate a distribution with different values of $\mu$ and $\sigma$? (Hint: read the [online documentation  for numpy.random.randn()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html))

## More Python exercises

### n-dimentional array of random numbers

In [5]:
# print a 2-dimentinal matix of random numbers
print(numpy.random.randn(3, 2))
# print a 3-dimentinal matix of random numbers
print(numpy.random.randn(3, 3, 4))

[[ 1.44124887 -0.73663035]
 [ 2.03575408 -2.61692691]
 [-2.00642537 -0.93275023]]
[[[ 0.51004579 -1.39206654 -1.32296471 -1.83039825]
  [-0.15879289  0.44303943  1.18136873 -1.32542613]
  [-0.17917593 -1.11180572  1.66166844 -0.97810241]]

 [[ 0.89848635  0.26730245 -2.17391158  0.4136864 ]
  [ 0.8457478  -1.51754397  0.72775841 -0.45646931]
  [ 0.91732559  0.57917099 -0.93150664  0.28428441]]

 [[-0.11704521  0.24071621 -0.90082023  1.16671914]
  [ 0.04902425  0.27517919 -1.49584234  0.26009235]
  [-0.19162538 -1.49580629  0.29071     0.13040491]]]


## Re-initializing the random seed!
run the following script to understand what happens if you re-initialize your random seed.

In [6]:
# import the essential  library
import numpy
# initialize a pseudorandom number generator
numpy.random.seed(1)
# print some random victors of with length  of 3
print(numpy.random.randn(3))
print(numpy.random.randn(3))
print(numpy.random.randn(3))
# note: if you initialize the pseudorandom number generator, you will go back to the beginning of the random series
print('pseudorandom number generator is initialized')
numpy.random.seed(1)
print(numpy.random.randn(3))
print(numpy.random.randn(3))
print(numpy.random.randn(3))

[ 1.62434536 -0.61175641 -0.52817175]
[-1.07296862  0.86540763 -2.3015387 ]
[ 1.74481176 -0.7612069   0.3190391 ]
pseudorandom number generator is initialized
[ 1.62434536 -0.61175641 -0.52817175]
[-1.07296862  0.86540763 -2.3015387 ]
[ 1.74481176 -0.7612069   0.3190391 ]
