# Simulate minimum deviation data

In [1]:
# Import packages
import numpy as np
rng = np.random.RandomState(0)

In [2]:
theta_deg = np.arange(45,85,5)
n0 = 1.67
alpha0_deg = 60
err_deg = 0.5/60

In [3]:
# Define model function
def model(theta_deg,n,alpha_deg):
    # Convert from degrees to radians, and add '0j' to theta so it is treated as a complex variable
    theta = np.deg2rad(theta_deg) + 0j
    alpha = np.deg2rad(alpha_deg)
    # Compute delta
    delta = theta + np.arcsin(np.sin(alpha)*np.sqrt(n**2-np.sin(theta)**2)- np.sin(theta)*np.cos(alpha)) - alpha
    # Warn the user if the argument of arcsin exceeds one
    if any(np.sin(alpha)*np.sqrt(n**2-np.sin(theta)**2)- np.sin(theta)*np.cos(alpha))>1:
        warnings.warn('Argument to arcsin exceeds one, returning the complex norm')
    #  Take the absolute value and convert to back to degrees
    delta_deg = np.rad2deg(np.absolute(delta))
    return delta_deg

In [4]:
delta = model(theta_deg,n0,alpha0_deg) + err_deg*rng.randn(*theta_deg.shape)
delta_deg = np.floor(delta)
delta_min = np.round(60*(delta-delta_deg))

In [5]:
data = np.column_stack((theta_deg,delta_deg,delta_min))

In [6]:
print(data)

[[45. 58.  5.]
 [50. 54. 26.]
 [55. 53. 18.]
 [60. 53. 30.]
 [65. 54. 37.]
 [70. 56. 31.]
 [75. 59. 11.]
 [80. 62. 30.]]


In [7]:
np.savetxt('mindevdatasim.csv',data,\
           fmt='%d',\
           delimiter=',',\
           header='theta (deg), delta (deg), delta (min)',\
           comments='')